apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: GAfdfPDKME7ZaBu0CR17D99aHFiImM0tJl+1rO9jIeo=
      - identity: {} # this fallback allows reading unencrypted secrets;
                                                    # for example, during initial migrati
                                                  
                                                      
