---
global:
  latestTag: 3594a2292cb5d74c0705173d881559a6724ff503
  overrideTag: 3374644783947859606776966857fff554feeh
  
  app:
    name: accounting-flink-jobs
    env: production

ws-flink-service:
  jarURI: local:///opt/flink/usrlib/application.jar
  stateBucketName: accounting-flink-jobs-production-flink
  flinkConfiguration:
    state.backend.rocksdb.predefined-options: "FLASH_SSD_OPTIMIZED"
    state.backend.rocksdb.checkpoint.transfer.thread.num: "2"
    state.backend.rocksdb.block.cache-size: "8MB"
    state.backend.rocksdb.writebuffer.size: "64MB"
    state.backend.rocksdb.writebuffer.count: "2"
    state.backend.rocksdb.thread.num: "2"
    state.backend.incremental: "true"
    state.backend.rocksdb.metrics.estimate-live-data-size: "true"
    state.backend.rocksdb.metrics.estimate-num-keys: "true"
    state.backend: "rocksdb"
    yarn.per-job-cluster.include-user-jar: "DISABLED"
    web.cancel.enable: "true"
    kubernetes.taskmanager.cpu.limit-factor: "5.0"
    kubernetes.jobmanager.cpu.limit-factor: "5.0"


  jobs:
    - name: book-value-calc
      image: 526316940316.dkr.ecr.ca-central-1.amazonaws.com/wealthsimple/accounting-flink-jobs-book-value-calculator
      entryClass: com.wealthsimple.accountingflinkjobs.bookvalue.MainKt
      flinkVersion: v1_14
      ephemeralVolume:
        storageSize: '256Gi'
        mountPath: '/opt/flink/data'
      jobManager:
        resource:
          memory: 4096m
      taskManager:
        resource:
          memory: 16384m
          cpu: 2
      numberOfTaskSlots: 6
      parallelism: 60
      flinkConfiguration:
        io.tmp.dirs: '/opt/flink/data'
        state.backend.rocksdb.checkpoint.transfer.thread.num: "8"

    - name: book-value-calc
      image: 22648499440316.dkr.ecr.ca-central-1.amazonaws.com/wealthsimple/accounting-hide-my-asses
      entryClass: com.wealthsimple.accountingflinkjobs.bookvalue.MainKt
      flinkVersion: v1_14
      ephemeralVolume:
        storageSize: '256Gi'
        mountPath: '/opt/flink/data'
      jobManager:
        resource:
          memory: 4096m
      taskManager:
        resource:
          memory: 16384m
          cpu: 2
      numberOfTaskSlots: 6
      parallelism: 60
      flinkConfiguration:
        io.tmp.dirs: '/opt/flink/data'
        state.backend.rocksdb.checkpoint.transfer.thread.num: "8"
    
  app:
    env: internal
    name: bullybot

ws-service:
  image: 526316940316.dkr.ecr.us-east-1.amazonaws.com/wealthsimple/bullybot
  memory: 2048Mi
  cpu: 250m

  secrets:
    files:
      create: true

  volumes:
    - name: bullybot-files
      secret:
        secretName: bullybot-files

  deployments:
    - args:
        - ddtrace-run
        - gunicorn
        - --workers=4
        - --bind=0.0.0.0:4000
        - app.app:app
      healthCheckUri: /healthcheck
      name: bullybot
      port: '4000'
      ingress: 'private'
      volumeMounts:
        - name: bullybot-files
          mountPath: /usr/src/app/google-service-account-private-key.pem.yaml
          # This is the secret name from SSM path /<cluster>/eks/bullybot/files/google-service-account-private-key
          subPath: google-service-account-private-key

  env:
    APP_ENV: production
    DATADOG_ENV: production
    DATADOG_SERVICE_NAME: bullybot
    DD_STATSD_SOCKET_PATH: /var/run/datadog/dsd.sock
    SERVER_NAME: bullybot-k8s.iad.w10external.com
