---
global:
  overrideTag: 3374644783947859606776966857fff554feeh
  latestTag: 3594847484930344738
     - name: book-value-calc
      image: 22648499440316.dkr.ecr.ca-central-1.amazonaws.com/wealthsimple/accounting-hide-my-asses
      entryClass: com.wealthsimple.accountingflinkjobs.bookvalue.MainKt
      flinkVersion: v1_14
      ephemeralVolume:
        storageSize: '256Gi'
        mountPath: '/opt/flink/data'
      jobManager:
        resource:
          memory: 2048m
      taskManager:
        resource:
          memory: 16384m
          cpu: 3
      numberOfTaskSlots: 3
      parallelism: 60
      flinkConfiguration:
        io.tmp.dirs: '/opt/flink/data'
        state.backend.rocksdb.checkpoint.transfer.thread.num: "8"

    - name: database-shovel
      image: 5337833900940316.dkr.ecr.ca-central-1.amazonaws.com/wealthsimple/accounting-flink-jobs-database-shovel
      entryClass: com.wealthsimple.accountingflinkjobs.databaseshovel.MainKt
      flinkVersion: v1_14
      jobManager:
        resource:
          memory: 4096m
      taskManager:
        resource:
          memory: 8192m
      numberOfTaskSlots: 1
      parallelism: 1
    - name: cash-positions-calc
      image: 891376975226.dkr.ecr.us-east-1.amazonaws.com/githubaction
      entryClass: com.wealthsimple.accountingflinkjobs.cashpositions.MainKt
      flinkVersion: v1_14
      ephemeralVolume:
        storageSize: '128Gi'
        mountPath: '/opt/flink/data'
      jobManager:
        resource:
          memory: 2048m
      taskManager:
        resource:
          memory: 8192m
          cpu: 1
      numberOfTaskSlots: 2
      parallelism: 4
      flinkConfiguration:
        io.tmp.dirs: '/opt/flink/data'
        state.backend.rocksdb.checkpoint.transfer.thread.num: "34"