name: ECR Image Tag Validation

on:
  pull_request:
    paths:
      - '**/values*.yaml'
  push:
    paths:
      - '**/values*.yaml'

jobs:
  validate_image_tags:
    name: Validate Image Tags
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Pull Request
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Cache repository state
        uses: actions/cache@v2
        with:
          path: |
            path/to/cache-directory
          key: ${{ runner.os }}-build-${{ hashFiles('**/values*.yaml') }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Identify Values Files
        id: identify-values-files
        run: |
          #!/bin/bash

          echo "Searching for values*.yaml files..."
          values_files=$(find . -type f -name "values*.yaml")

          if [ -n "$values_files" ]; then
              echo "Values*.yaml files found:"
              echo "$values_files"
              echo "::set-output name=values_files::$values_files"
          else
              echo "No values*.yaml files found."
              exit 1
          fi

          overrideTag=""
          image=""
          latestTag=""

          for file in $values_files; do
              echo "Processing $file..."
              while IFS= read -r line; do
                  if [[ $line =~ image:\ (.+) ]]; then
                      image="${BASH_REMATCH[1]}"
                      echo "Image: $image"
                  fi
                  if [[ $line =~ overrideTag:\ (.+) ]]; then
                      overrideTag="${BASH_REMATCH[1]}"
                      echo "OverrideTag: $overrideTag"
                  fi
              done < "$file"
              if [[ -n "$image" && -n "$overrideTag" ]]; then
                  break
              fi
          done

          if [[ -z "$overrideTag" ]]; then
              echo "OverrideTag not found. Checking for latestTag..."
              for file in $values_files; do
                  echo "Processing $file..."
                  while IFS= read -r line; do
                      if [[ $line =~ latestTag:\ (.+) ]]; then
                          latestTag="${BASH_REMATCH[1]}"
                          echo "Latest Tag: $latestTag"
                          break 
                      fi
                  done < "$file"
                  if [[ -n "$latestTag" ]]; then
                      break
                  fi
              done
          fi

          echo "::set-output name=overrideTag::$overrideTag"
          echo "::set-output name=image::$image"
          echo "::set-output name=latestTag::$latestTag"

      - name: Login to Amazon ECR
        run: |
           images=$(yq eval-all '.image' ${{ steps.identify-values-files.outputs.values_files }})
            for image_uri in $images; do
              account_id=$(echo "$image_uri" | cut -d'.' -f1)
              region=$(echo "$image_uri" | cut -d'.' -f4)   
              echo "Logging in to Amazon ECR for image: $image_uri"
              aws ecr get-login-password --region "$region" | docker login --username AWS --password-stdin "$account_id.dkr.ecr.$region.amazonaws.com"
           done
    
      - name: List ECR Repositories
        id: list-ecr-repos
        run: |
          echo "Listing ECR repositories..."
          aws ecr describe-repositories --query 'repositories[*].[repositoryName, repositoryUri]'
          echo "::set-output name=ecr_repositories::$(aws ecr describe-images --query 'repositories[*].[repositoryName, repositoryUri, imageTags[*]]' --output table)"

      - name: Check Overrides and Validate Image Tags in ECR
        if: ${{ steps.identify-values-files.outputs.values_files != '' }}
        run: |
          overrideTag=${{ steps.identify-values-files.outputs.overrideTag }}
          latestTag=${{ steps.identify-values-files.outputs.latestTag }}
          image=${{ steps.identify-values-files.outputs.image }}
          ecr_repositories=$(echo "${{ steps.list-ecr-repos.outputs.ecr_repositories }}")

          if [[ -n "$overrideTag" || -n "$latestTag" ]]; then
              echo "Checking overrideTag/latestTag against ECR repositories..."
              tagToPair=""
              if [[ -n "$overrideTag" && $(echo "$ecr_repositories" | grep -q "$overrideTag") ]]; then
                  echo "OverrideTag '$overrideTag' found in ECR. Validation successful."
                  tagToPair="$overrideTag"
              elif [[ -n "$latestTag" && $(echo "$ecr_repositories" | grep -q "$latestTag") ]]; then
                  echo "LatestTag '$latestTag' found in ECR. Validation successful."
                  tagToPair="$latestTag"
              else
                  echo "Error: Neither OverrideTag nor LatestTag found in ECR repository. Validation failed."
              fi

              if [[ $(echo "$ecr_repositories" | grep -q "$image") ]]; then
                  echo "Image '$image' found in ECR. Pairing with $tagToPair..."
                  echo "Image: $image, Tag: $tagToPair"
              else
                  echo "Error: Image '$image' not found in ECR repository. Validation failed."
                  exit 1
              fi

              exit 0
          else
              echo "Error: Neither OverrideTag nor LatestTag provided. Validation failed."
              exit 1
          fi

      - name: Display Validation Result
        run: |
          if [ $? -eq 0 ]; then
              echo "Validation successful. All image tags are valid."
          else
              echo  "Validation failed. There are issues with the image tags."
          fi