---
name: ECR Image Tag Validation

on:
  pull_request:
    paths:
      - '**/values*.yaml'
  push:
    paths:
      - '**/values*.yaml'

jobs:
  validate_image_tags:
    name: Validate Image Tags
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Pull Request
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Cache repository state
        uses: actions/cache@v2
        with:
          path: |
            path/to/cache-directory
          key: ${{ runner.os }}-build-${{ hashFiles('**/values*.yaml') }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR in us-east-1
        uses: aws-actions/amazon-ecr-login@v2

      - name: Identify Values Files
        id: identify-values-files
        run: |
          #!/bin/bash
          # Search for values*.yaml files in the current directory and all subdirectories
          echo "Searching for values*.yaml files..."
          values_files=$(find . -type f -name "values*.yaml")
          # Check if any values*.yaml files were found
          if [ -n "$values_files" ]; then
              echo "Values*.yaml files found:"
              echo "$values_files"
              # Set an output for values files found
              echo "::set-output name=values_files::$values_files"
          else
              echo "No values*.yaml files found."
              exit 1
          fi
          # Initialize variables for overrideTag, image, and latestTag
          overrideTag=""
          image=""
          latestTag=""
          # Extract overrideTag, image, and latestTag fields from values*.yaml files
          for file in $values_files; do
              echo "Processing $file..."
              while IFS= read -r line; do
                  # Check if overrideTag exists
                  if [[ $line =~ overrideTag:\ (.+) ]]; then
                      overrideTag="${BASH_REMATCH[1]}"
                      echo "OverrideTag: $overrideTag"
                      #continue
                  fi
                  # Check if image exists
                  if [[ $line =~ image:\ (.+) ]]; then
                      image="${BASH_REMATCH[1]}"
                      echo "Image: $image"
                  fi
                  # Check if latestTag exists only if overrideTag is not found
                  if [[ -z "$overrideTag" && $line =~ latestTag:\ (.+) ]]; then
                      latestTag="${BASH_REMATCH[1]}"
                      echo "Latest Tag: $latestTag"
                  fi
              done < "$file"
              # Check if overrideTag and image(s) are found, if not, break the loop and look for latestTag
              if [[ -n "$overrideTag" && -n "$image" ]]; then
                  break
              fi
          done
          # Check if overrideTag and image(s) are found, if not, echo that latestTag will be checked
          if [[ -z "$overrideTag" && -z "$image" ]]; then
              echo "OverrideTag and image(s) not found. Checking for latestTag..."
          fi
          
              # Output the images
              echo "::set-output name=images::${images[*]}"
          fi
          # Output the values to be used by the next steps
          echo "::set-output name=overrideTag::$overrideTag"
          echo "::set-output name=image::$image"
          # Output latestTag only if overrideTag is not found
          if [[ -z "$overrideTag" ]]; then
              echo "::set-output name=latestTag::$latestTag"
          fi

      - name: List ECR Repositories
        id: list-ecr-repos
        run: |
          echo "Listing ECR repositories..."
          aws ecr describe-repositories --query 'repositories[*].[repositoryName, repositoryUri]'
          echo "::set-output name=ecr_repositories::$(aws ecr describe-images --query 'repositories[*].[repositoryName, repositoryUri, imageTags[*]]' --output table)"

      - name: Check Overrides and Validate Image Tags in ECR
        if: ${{ steps.identify-values-files.outputs.values_files != '' }}
        run: |
          # Retrieve values from previous step outputs
          overrideTag=${{ steps.identify-values-files.outputs.overrideTag }}
          latestTag=${{ steps.identify-values-files.outputs.latestTag }}
          image=${{ steps.identify-values-files.outputs.image }}
          # Retrieve ECR repositories list
          ecr_repositories=$(echo "${{ steps.list-ecr-repos.outputs.ecr_repositories }}")

          # Check if overrideTag or latestTag exists in ECR repositories
          if [[ -n "$overrideTag" || -n "$latestTag" ]]; then
              echo "Checking overrideTag/latestTag against ECR repositories..."
              tagToPair=""
              if [[ -n "$overrideTag" && $(echo "$ecr_repositories" | grep -q "$overrideTag") ]]; then
                  echo "OverrideTag '$overrideTag' found in ECR. Validation successful."
                  tagToPair="$overrideTag"
              elif [[ -n "$latestTag" && $(echo "$ecr_repositories" | grep -q "$latestTag") ]]; then
                  echo "LatestTag '$latestTag' found in ECR. Validation successful."
                  tagToPair="$latestTag"
              else
                  echo "Error: Neither OverrideTag nor LatestTag found in ECR repository. Validation failed."
                
              fi

              # Check if the image exists in ECR repositories
              if [[ $(echo "$ecr_repositories" | grep -q "$image") ]]; then
                  echo "Image '$image' found in ECR. Pairing with $tagToPair..."
                  echo "Image: $image, Tag: $tagToPair"
              else
                  echo "Error: Image '$image' not found in ECR repository. Validation failed."
                  exit 1
              fi

              # Exit with success
              exit 0
          else
              # If neither overrideTag nor latestTag are found, exit with failure
              echo "Error: Neither OverrideTag nor LatestTag provided. Validation failed."
              exit 1
          fi
      - name: Display Validation Result
        run: |
          if [ $? -eq 0 ]; then
              echo "Validation successful. All image tags are valid."
          else
              echo  "Validation failed. There are issues with the image tags."
          fi

