name: ECR Image Tag Validation
on:
  pull_request:
    paths:
      - '**'
  push:
    paths:
      - '**'
jobs:
  validate_image_tags:
    name: Validate Image Tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Pull Request
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Identify Values Files
        id: identify-values-files
        run: |
          #!/bin/bash
          # Search for values*.yaml files in the current directory and all subdirectories
          echo "Searching for values*.yaml files..."
          values_files=$(find . -type f -name "values*.yaml")
          # Check if any values*.yaml files were found
          if [ -n "$values_files" ]; then
              echo "Values*.yaml files found:"
              echo "$values_files"
          else
              echo "No values*.yaml files found."
              exit 1
          fi
          # Initialize variables for overrideTag, image, and latestTag
          overrideTag=""
          image=""
          latestTag=""
          # Extract overrideTag, image, and latestTag fields from values*.yaml files
          for file in $values_files; do
              echo "Processing $file..."
              while IFS= read -r line; do
                  # Check if overrideTag exists
                  if [[ $line =~ overrideTag:\ (.+) ]]; then
                      overrideTag="${BASH_REMATCH[1]}"
                      echo "OverrideTag: $overrideTag"
                      continue
                  fi
                  # Check if image exists
                  if [[ $line =~ image:\ (.+) ]]; then
                      image="${BASH_REMATCH[1]}"
                      echo "Image: $image"
                  fi
                  # Check if latestTag exists
                  if [[ $line =~ latestTag:\ (.+) ]]; then
                      latestTag="${BASH_REMATCH[1]}"
                      echo "Latest Tag: $latestTag"
                  fi
              done < "$file"
              # Check if overrideTag and image(s) are found, if not, break the loop and look for latestTag
              if [[ -n "$overrideTag" && -n "$image" ]]; then
                  break
              fi
          done
          # Check if overrideTag and image(s) are found, if not, echo that latestTag will be checked
          if [[ -z "$overrideTag" && -z "$image" ]]; then
              echo "OverrideTag and image(s) not found. Checking for latestTag..."
          fi
          # Output the values to be used by the next steps
          echo "::set-output name=overrideTag::$overrideTag"
          echo "::set-output name=image::$image"
          echo "::set-output name=latestTag::$latestTag"
      
      - name: Pair Image with Tag
        run: |
          # Retrieve values from previous step outputs
          image=${{ steps.identify-values-files.outputs.image }}
          overrideTag=${{ steps.identify-values-files.outputs.overrideTag }}
          latestTag=${{ steps.identify-values-files.outputs.latestTag }}

          # Check if overrideTag exists, if not, pair with latestTag
          if [[ -n "$overrideTag" ]]; then
              echo "Pairing image with overrideTag..."
              echo "Image: $image, OverrideTag: $overrideTag"
          else
              echo "Pairing image with latestTag..."
              echo "Image: $image, Latest Tag: $latestTag"
          fi

      - name: List ECR Repositories
        run: |
          echo "Listing ECR repositories..."
          aws ecr describe-repositories --query 'repositories[*].[repositoryName, repositoryUri]' --output table
          
      - name: Check Overrides and Validate Image Tags in ECR
        if: ${{ steps.identify-values-files.outputs.values_files != '' }}
        run: |
          # Retrieve values from previous step outputs
          overrides=${{ steps.identify-values-files.outputs.overrides }}
          image=${{ steps.identify-values-files.outputs.image }}
          latestTag=${{ steps.identify-values-files.outputs.latestTag }}

          # Retrieve ECR repositories list
          ecr_repositories=$(echo "${{ steps.list-ecr-repos.outputs.ecr_repositories }}" | base64 -d)

          # Check if overrideTag exists in ECR repositories
          if [[ -n "$overrideTag" ]]; then
              echo "Checking overrideTag against ECR repositories..."
              if echo "$ecr_repositories" | grep -q "$overrideTag"; then
                  echo "OverrideTag '$overrideTag' found in ECR. Validation successful."
              else
                  echo "Error: OverrideTag '$overrideTag' not found in ECR repository. Validation failed."
                  exit 1
              fi
          fi

          # Check if image and latest tag combination exists in ECR repositories
          if [[ -n "$image" && -n "$latestTag" ]]; then
              echo "Checking image and latest tag against ECR repositories..."
              if echo "$ecr_repositories" | grep -q "$image" && echo "$ecr_repositories" | grep -q "$latestTag"; then
                  echo "Image '$image' with latest tag '$latestTag' found in ECR. Validation successful."
              else
                  echo "Error: Image '$image' with latest tag '$latestTag' not found in ECR repository. Validation failed."
                  exit 1
              fi
          fi

      - name: Set Workflow Status
        if: ${{ steps.identify-values-files.outputs.values_files != '' }}
        run: exit 0
