---
name: ECR Image Tag Validation

on:
  pull_request:
    paths:
      - '**'
  push:
    paths:
      - '**'

jobs:

  validate_image_tags:
    name: Validate Image Tags
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Pull Request
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Identify Values Files
        id: identify-values-files
        run: |
          #!/bin/bash

          # Search for values*.yaml files in the current directory and all subdirectories
          echo "Searching for values*.yaml files..."
          values_files=$(find . -type f -name "values*.yaml")

          # Check if any values*.yaml files were found
          if [ -n "$values_files" ]; then
              echo "Values*.yaml files found:"
              echo "$values_files"
          else
              echo "No values*.yaml files found here."
          fi

      - name: Find Latest Tag and Image String
        id: find-latest-tag
        run: |
          for file in "${{ steps.identify-values-files.outputs.values_files }}"; do
            latest_tag=$(grep -oE 'latestTag: (.*)' "$file" | awk '{print $2}')
            image_string=$(grep -oE 'image: "(.*)" # Replace this regex with your specific pattern' "$file" | cut -d'"' -f2)
            echo "Latest Tag: $latest_tag"
            echo "Image String: $image_string"
            echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV
            echo "IMAGE_STRING=$image_string" >> $GITHUB_ENV
          done
